version = 3.8.2

runner.dialect = scala3

preset = default
maxColumn = 100

align.tokens."+" = [
  { code = "extends", owner = "Template" },
  { code = "//",      owner = ".*" },
  { code = "{",       owner = "Template" },
  { code = "}",       owner = "Template" },
  { code = "->",      owner = "Term.ApplyInfix" },
  { code = "<-",      owner = "Enumerator.Generator" },
  { code = "%",       owner = "Term.ApplyInfix"},
  { code = "%%",      owner = "Term.ApplyInfix"},
  { code = "=",       owner = "(Enumerator.Val|Defn.(Va(l|r)|Def|Type))" }
]
align.openParenDefnSite = true
align.openParenCallSite = true

verticalMultiline.atDefnSite = false

danglingParentheses.preset = false
includeCurlyBraceInSelectChains = false

newlines.avoidAfterYield = false
newlines.beforeCurlyLambdaParams = multilineWithCaseOnly

rewrite.rules = [SortImports, RedundantBraces, RedundantParens, PreferCurlyFors]

project.git = true
lineEndings = preserve
docstrings.wrap = no

spaces.beforeContextBoundColon = Always

fileOverride {
  "glob:**/domain/src/**/scala/*.scala" {
    runner.dialect = scala211
  }
  "glob:**/cql-schemas/src/**/*.scala" {
    runner.dialect = scala3
    rewrite.scala3.convertToNewSyntax = true
    rewrite.scala3.removeOptionalBraces = yes
  }
  "glob:**/cosine-service/src/**/*.scala" {
    runner.dialect = scala3
    rewrite.scala3.convertToNewSyntax = true
    rewrite.scala3.removeOptionalBraces = yes
  }
  "glob:**/lookup-service/src/**/*.scala" {
    runner.dialect = scala3
    rewrite.scala3.convertToNewSyntax = true
    rewrite.scala3.removeOptionalBraces = yes
  }
  "glob:**/more-like-this-api/src/**/*.scala" {
    runner.dialect = scala3
    rewrite.scala3.convertToNewSyntax = true
    rewrite.scala3.removeOptionalBraces = yes
  }
  "glob:**/cosine-generation/src/**/scala/*.scala" {
    runner.dialect = scala211
  }
  "glob:**/lookup-generation/src/**/scala/*.scala" {
    runner.dialect = scala211
  }
  "glob:**/spark-common/src/**/scala/*.scala" {
    runner.dialect = scala211
  }
}

project.excludeFilters = [
  ".*AssembledOffer\\.scala"
  ".*EntitiesToLookupsSpec\\.scala"
]
